name = "clipboard-shuttle"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "clipboard-d1"
database_id = "77e767d8-f3c6-43fe-887b-c6cb33bfeaa1"
